[build-system]
requires = ["setuptools>=42", "wheel"]
build-backend = "setuptools.build_meta"

[project]
name = "jobsight"
version = "1.0.0"
description = "Jobsight - Job Posting Platform"
readme = "README.md"
requires-python = ">=3.9,<3.10"
license = {text = "Proprietary"}
