# Generated by Django 5.1.7 on 2025-05-25 14:16

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0031_pricingpackage_pricingfeature'),
    ]

    operations = [
        migrations.AddField(
            model_name='joblisting',
            name='view_count',
            field=models.PositiveIntegerField(default=0, verbose_name='ნახვების რაოდენობა'),
        ),
    ]
