# Generated by Django 5.1.7 on 2025-05-26 11:09

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0032_joblisting_view_count'),
    ]

    operations = [
        migrations.AddField(
            model_name='pricingpackage',
            name='has_discount_badge',
            field=models.BooleanField(default=True, verbose_name='Show Discount Badge'),
        ),
    ]
