# Generated by Django 5.1.7 on 2025-05-26 16:15

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0033_add_discount_badge_to_pricing_package'),
    ]

    operations = [
        migrations.AddField(
            model_name='userprofile',
            name='desired_field',
            field=models.CharField(blank=True, choices=[('მენეჯმენტი/ადმინისტრირება', 'მენეჯმენტი/ ადმინისტრირება'), ('მარკეტინგი', 'მარკეტინგი'), ('ფინანსები', 'ფინანსები'), ('გაყიდვები/მომხმარებელთან ურთიერთობა', 'გაყიდვები/მომხმარებელთან ურთიერთობა'), ('IT/პროგრამირება', 'IT/პროგრამირება'), ('დიზაინი', 'დიზაინი'), ('ჰორეკა/კვება', 'ჰორეკა/კვება'), ('დაცვა', 'დაცვა'), ('სილამაზე/მოდა', 'სილამაზე/მოდა'), ('მშენებლობა', 'მშენებლობა'), ('მედიცინა', 'მედიცინა'), ('განათლება', 'განათლება'), ('სამართალი', 'სამართალი'), ('ტურიზმი', 'ტურიზმი'), ('ლოჯისტიკა/დისტრიბუცია', 'ლოჯისტიკა/დისტრიბუცია'), ('საბანკო საქმე', 'საბანკო საქმე'), ('აზარტული', 'აზარტული')], max_length=100, null=True, verbose_name='სასურველი სფერო'),
        ),
        migrations.AddField(
            model_name='userprofile',
            name='field_experience',
            field=models.CharField(blank=True, choices=[('გამოცდილების გარეშე', 'გამოცდილების გარეშე'), ('დამწყები', 'დამწყები'), ('საშუალო დონე', 'საშუალო დონე'), ('პროფესიონალი', 'პროფესიონალი')], max_length=100, null=True, verbose_name='გამოცდილება'),
        ),
        migrations.AddField(
            model_name='userprofile',
            name='visible_to_employers',
            field=models.BooleanField(default=False, verbose_name='ხილვადია დამსაქმებლებისთვის'),
        ),
        migrations.AlterField(
            model_name='joblisting',
            name='status',
            field=models.CharField(choices=[('pending_review', 'Pending Review'), ('approved', 'Approved'), ('rejected', 'Rejected'), ('expired', 'Expired')], db_index=True, default='pending_review', max_length=20, verbose_name='სტატუსი'),
        ),
    ]
