# Generated by Django 5.1.7 on 2025-05-27 13:14

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0034_userprofile_desired_field_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='employerprofile',
            name='show_phone_number',
            field=models.BooleanField(default=True, verbose_name='გამოჩნდეს ტელეფონის ნომერი პროფილზე'),
        ),
    ]
