# Generated by Django 5.1.7 on 2025-05-27 20:10

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0035_employerprofile_show_phone_number'),
    ]

    operations = [
        migrations.AlterField(
            model_name='employerprofile',
            name='company_logo',
            field=models.ImageField(blank=True, null=True, upload_to='company_logos/', verbose_name='კომპანიის ლოგო'),
        ),
        migrations.AlterField(
            model_name='jobapplication',
            name='resume',
            field=models.FileField(upload_to='resumes/', verbose_name='რეზიუმე'),
        ),
        migrations.AlterField(
            model_name='userprofile',
            name='cv',
            field=models.FileField(blank=True, null=True, upload_to='cvs/', verbose_name='CV'),
        ),
        migrations.AlterField(
            model_name='userprofile',
            name='profile_picture',
            field=models.ImageField(blank=True, null=True, upload_to='profile_pictures/', verbose_name='პროფილის სურათი'),
        ),
    ]
