# Generated by Django 5.1.7 on 2025-05-28 22:36

from django.db import migrations, models


def convert_rejection_reasons(apps, schema_editor):
    """
    Map old rejection reason keys to new ones
    """
    RejectionReason = apps.get_model('core', 'RejectionReason')
    
    # Map old keys to new keys
    key_mapping = {
        'ლოკაცია': 'შეუსაბამო_საცხოვრებელი_ადგილი',
        'არასაკმარისი_ინფორმაცია': 'სივიში_არ_არის_საკმარისი_ინფორმაცია',
        # Add other mappings if needed
    }
    
    # Update each reason
    for old_key, new_key in key_mapping.items():
        reasons = RejectionReason.objects.filter(name=old_key)
        for reason in reasons:
            reason.name = new_key
            reason.save()


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0036_alter_employerprofile_company_logo_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='rejectionreason',
            name='name',
            field=models.CharField(choices=[('ენის_ცოდნის_ნაკლებობა', 'ენის ცოდნის ნაკლებობა'), ('არასაკმარისი_გამოცდილება', 'არასაკმარისი გამოცდილება'), ('უნარების_ნაკლებობა', 'უნარების ნაკლებობა'), ('შეუსაბამო_საცხოვრებელი_ადგილი', 'შეუსაბამო საცხოვრებელი ადგილი'), ('სივიში_არ_არის_საკმარისი_ინფორმაცია', 'სივიში არ არის საკმარისი ინფორმაცია'), ('განათლების_შეუსაბამობა', 'განათლების შეუსაბამობა'), ('კარიერული_მიზნების_შეუსაბამობა', 'კარიერული მიზნების შეუსაბამობა'), ('სივის_ფორმატის_სტრუქტურის_ხარვეზები', 'სივის ფორმატის/სტრუქტურის ხარვეზები'), ('სერთიფიკატების_ლიცენზიების_ნაკლებობა', 'სერთიფიკატების/ლიცენზიების ნაკლებობა'), ('არარელევანტური_სამუშაო_ისტორია', 'არარელევანტური სამუშაო ისტორია')], max_length=100, unique=True, verbose_name='მიზეზი'),
        ),
        migrations.RunPython(convert_rejection_reasons),
    ]
