# Generated by Django 5.1.7 on 2025-05-29 17:18

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0037_update_rejection_reason_choices'),
    ]

    operations = [
        migrations.CreateModel(
            name='ComparisonTable',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(default='პაკეტების შედარება', max_length=255, verbose_name='Table Title')),
                ('subtitle', models.CharField(default='დეტალური შედარება, რომ აირჩიოთ თქვენი ბიზნესისთვის შესაფერისი პაკეტი', max_length=255, verbose_name='Table Subtitle')),
                ('is_active', models.BooleanField(default=True, verbose_name='Active')),
            ],
            options={
                'verbose_name': 'Comparison Table',
                'verbose_name_plural': 'Comparison Tables',
            },
        ),
        migrations.CreateModel(
            name='ComparisonRow',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('feature_name', models.CharField(max_length=255, verbose_name='Feature Name')),
                ('display_type', models.CharField(choices=[('text', 'Text'), ('checkmark', 'Checkmark'), ('badge', 'Badge'), ('special', 'Special Format')], default='checkmark', max_length=20, verbose_name='Display Type')),
                ('display_order', models.PositiveSmallIntegerField(default=0, verbose_name='Display Order')),
                ('standard_value', models.CharField(blank=True, max_length=255, verbose_name='Standard Value')),
                ('standard_included', models.BooleanField(default=False, verbose_name='Included in Standard')),
                ('premium_value', models.CharField(blank=True, max_length=255, verbose_name='Premium Value')),
                ('premium_included', models.BooleanField(default=True, verbose_name='Included in Premium')),
                ('premium_plus_value', models.CharField(blank=True, max_length=255, verbose_name='Premium Plus Value')),
                ('premium_plus_included', models.BooleanField(default=True, verbose_name='Included in Premium Plus')),
                ('table', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='rows', to='core.comparisontable', verbose_name='Comparison Table')),
            ],
            options={
                'verbose_name': 'Comparison Row',
                'verbose_name_plural': 'Comparison Rows',
                'ordering': ['display_order', 'id'],
            },
        ),
    ]
