# Generated by Django 5.1.7 on 2025-05-29 19:25

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0039_blogcategory_blogtag_blogpost_blogpostcategory_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='employerprofile',
            name='has_cv_database_access',
            field=models.BooleanField(default=False, verbose_name='წვდომა სივების ბაზაზე'),
        ),
    ]
