# Generated by Django 5.1.7 on 2025-06-01 22:18
# Note: This migration requires the django-ckeditor package to be installed
# even though we're transitioning to django-ckeditor-5. This is why both packages
# are included in requirements.txt and INSTALLED_APPS.

from django.db import migrations
import django.db.models.fields


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0041_userprofile_is_email_verified_emailverificationtoken'),
    ]

    operations = [
        migrations.AlterField(
            model_name='blogpost',
            name='content',
            field=django.db.models.fields.TextField(verbose_name='კონტენტი'),
        ),
        migrations.AlterField(
            model_name='employerprofile',
            name='company_description',
            field=django.db.models.fields.TextField(blank=True, verbose_name='კომპანიის აღწერა'),
        ),
        migrations.AlterField(
            model_name='joblisting',
            name='description',
            field=django.db.models.fields.TextField(verbose_name='ვაკანსიის აღწერა'),
        ),
    ]
