# Generated by Django 5.1.7 on 2025-06-01 22:18

import ckeditor.fields
from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0041_userprofile_is_email_verified_emailverificationtoken'),
    ]

    operations = [
        migrations.AlterField(
            model_name='blogpost',
            name='content',
            field=ckeditor.fields.RichTextField(verbose_name='კონტენტი'),
        ),
        migrations.AlterField(
            model_name='employerprofile',
            name='company_description',
            field=ckeditor.fields.RichTextField(blank=True, verbose_name='კომპანიის აღწერა'),
        ),
        migrations.AlterField(
            model_name='joblisting',
            name='description',
            field=ckeditor.fields.RichTextField(verbose_name='ვაკანსიის აღწერა'),
        ),
    ]
