# Generated by Django 5.1.7 on 2025-06-01 22:25

import django_ckeditor_5.fields
from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0042_alter_blogpost_content_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='blogpost',
            name='content',
            field=django_ckeditor_5.fields.CKEditor5Field(verbose_name='კონტენტი'),
        ),
        migrations.AlterField(
            model_name='employerprofile',
            name='company_description',
            field=django_ckeditor_5.fields.CKEditor5Field(blank=True, verbose_name='კომპანიის აღწერა'),
        ),
        migrations.AlterField(
            model_name='joblisting',
            name='description',
            field=django_ckeditor_5.fields.CKEditor5Field(verbose_name='ვაკანსიის აღწერა'),
        ),
    ]
