# Generated by Django 5.1.7 on 2025-06-01 22:47

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0043_alter_blogpost_content_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='blogpost',
            name='content',
            field=models.TextField(verbose_name='კონტენტი'),
        ),
        migrations.AlterField(
            model_name='employerprofile',
            name='company_description',
            field=models.TextField(blank=True, verbose_name='კომპანიის აღწერა'),
        ),
        migrations.AlterField(
            model_name='joblisting',
            name='description',
            field=models.TextField(verbose_name='ვაკანსიის აღწერა'),
        ),
    ]
