# Generated by Django 5.1.7 on 2025-06-02 09:09
# This merge migration resolves conflicts between two parallel migration paths:
# 1. 0042 -> 0043_alter_blogpost_content_and_more -> 0044 -> 0045
# 2. 0042 -> 0043_update_ckeditor_fields
# Both paths update the same fields to use CKEditor5Field.

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0043_update_ckeditor_fields'),
        ('core', '0045_alter_blogpost_content_and_more'),
    ]

    operations = [
    ]
