# Generated by Django 5.1.7 on 2025-06-02 09:09

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0043_update_ckeditor_fields'),
        ('core', '0045_alter_blogpost_content_and_more'),
    ]

    operations = [
    ]
