# Generated by Django 5.1.7 on 2025-06-02 12:30

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0047_alter_blogpost_featured_image_and_more'),
    ]

    operations = [
        migrations.CreateModel(
            name='CVAccess',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('accessed_at', models.DateTimeField(auto_now_add=True)),
                ('candidate_profile', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='cv_accesses', to='core.userprofile')),
                ('employer_profile', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='cv_accesses', to='core.employerprofile')),
            ],
            options={
                'verbose_name': 'CV წვდომა',
                'verbose_name_plural': 'CV წვდომები',
            },
        ),
    ]
