# Generated by Django 5.1.7 on 2025-06-02 17:38

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0048_cvaccess'),
    ]

    operations = [
        migrations.AlterField(
            model_name='jobapplication',
            name='status',
            field=models.CharField(choices=[('განხილვის_პროცესში', 'განხილვის პროცესში'), ('ნანახი', 'ნანახი'), ('გასაუბრება', 'გასაუბრება'), ('რეზერვი', 'რეზერვი')], db_index=True, default='განხილვის_პროცესში', max_length=30, verbose_name='სტატუსი'),
        ),
    ]
