# Generated by Django 5.1.7 on 2025-06-02 18:36

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0049_alter_jobapplication_status'),
    ]

    operations = [
        migrations.AddField(
            model_name='jobapplication',
            name='cv_viewed',
            field=models.BooleanField(db_index=True, default=False, verbose_name='CV ნანახია'),
        ),
        migrations.AlterField(
            model_name='jobapplication',
            name='status',
            field=models.CharField(choices=[('განხილვის_პროცესში', 'განხილვის პროცესში'), ('გასაუბრება', 'გასაუბრება'), ('რეზერვი', 'რეზერვი')], db_index=True, default='განხილვის_პროცესში', max_length=30, verbose_name='სტატუსი'),
        ),
    ]
