# Generated by Django 5.1.7 on 2025-06-02 18:45

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0050_jobapplication_cv_viewed_alter_jobapplication_status'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='jobapplication',
            name='cv_viewed',
        ),
        migrations.AddField(
            model_name='jobapplication',
            name='is_viewed',
            field=models.BooleanField(db_index=True, default=False, verbose_name='ნანახია'),
        ),
    ]
