# Generated by Django 5.1.7 on 2025-06-13 22:15

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0053_ckeditor4_to_ckeditor5_transition'),
    ]

    operations = [
        migrations.AlterField(
            model_name='employerprofile',
            name='show_phone_number',
            field=models.BooleanField(default=False, verbose_name='გამოჩნდეს ტელეფონის ნომერი პროფილზე'),
        ),
    ]
