# Generated by Django 5.1.7 on 2025-06-23 15:33

import ckeditor.fields
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0056_alter_joblisting_category_alter_joblisting_location_and_more'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.RemoveIndex(
            model_name='blogpost',
            name='core_blogpo_status_cfd0fd_idx',
        ),
        migrations.AlterField(
            model_name='blogpost',
            name='content',
            field=ckeditor.fields.RichTextField(verbose_name='კონტენტი'),
        ),
        migrations.AlterField(
            model_name='userprofile',
            name='desired_field',
            field=models.CharField(blank=True, choices=[], max_length=100, null=True, verbose_name='სასურველი სფერო'),
        ),
        migrations.AlterField(
            model_name='userprofile',
            name='field_experience',
            field=models.CharField(blank=True, choices=[], max_length=100, null=True, verbose_name='გამოცდილება'),
        ),
        migrations.AddIndex(
            model_name='blogpost',
            index=models.Index(fields=['-published_at'], name='core_blogpo_publish_4753d4_idx'),
        ),
        migrations.AddIndex(
            model_name='blogpost',
            index=models.Index(fields=['status'], name='core_blogpo_status_032da8_idx'),
        ),
    ]
