# Generated by Django 5.1.7 on 2025-06-23 16:59

import ckeditor.fields
from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0057_remove_blogpost_core_blogpo_status_cfd0fd_idx_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='employerprofile',
            name='company_description',
            field=ckeditor.fields.RichTextField(blank=True, verbose_name='კომპანიის აღწერა'),
        ),
        migrations.AlterField(
            model_name='joblisting',
            name='description',
            field=ckeditor.fields.RichTextField(verbose_name='ვაკანსიის აღწერა'),
        ),
    ]
