# Generated by Django 5.1.7 on 2025-06-25 17:34

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0058_alter_employerprofile_company_description_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='userprofile',
            name='sms_notifications',
            field=models.BooleanField(default=False, verbose_name='თანახმა ვარ მივიღო SMS შეტყობინებები'),
        ),
    ]
