# Generated by Django 5.1.7 on 2025-06-25 17:43

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0059_userprofile_sms_notifications'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='userprofile',
            name='sms_notifications',
        ),
        migrations.AddField(
            model_name='userprofile',
            name='email_notifications',
            field=models.BooleanField(default=False, verbose_name='თანახმა ვარ მივიღო ელ-ფოსტის შეტყობინებები'),
        ),
    ]
