# Generated by Django 5.1.7 on 2025-06-25 21:37

import ckeditor.fields
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0060_remove_userprofile_sms_notifications_and_more'),
    ]

    operations = [
        migrations.CreateModel(
            name='StaticPage',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=200, verbose_name='Title')),
                ('page_type', models.CharField(choices=[('privacy_policy', 'Privacy Policy'), ('terms_conditions', 'Terms & Conditions')], max_length=50, unique=True, verbose_name='Page Type')),
                ('content', ckeditor.fields.RichTextField(verbose_name='Content')),
                ('last_updated', models.DateTimeField(auto_now=True, verbose_name='Last Updated')),
            ],
            options={
                'verbose_name': 'Static Page',
                'verbose_name_plural': 'Static Pages',
            },
        ),
    ]
