# Generated by Django 5.1.7 on 2025-06-29 17:58

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0062_add_cvaccess_unique_constraint'),
    ]

    operations = [
        migrations.AddField(
            model_name='joblisting',
            name='external_link',
            field=models.URLField(blank=True, verbose_name='External Link'),
        ),
        migrations.AddField(
            model_name='joblisting',
            name='use_external_link',
            field=models.BooleanField(default=False, verbose_name='ატვირთულია გარე ლინკით'),
        ),
    ]
