# Generated by Django 5.1.7 on 2025-06-30 16:43

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0063_joblisting_external_link_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='joblisting',
            name='status',
            field=models.CharField(choices=[('pending_review', 'Pending Review'), ('approved', 'Approved'), ('rejected', 'Rejected'), ('expired', 'Expired'), ('extended_review', 'Extended (Under Review)')], db_index=True, default='pending_review', max_length=20, verbose_name='სტატუსი'),
        ),
    ]
