# Generated by Django 5.1.7 on 2025-06-30 17:23

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0064_alter_joblisting_status'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='joblisting',
            options={'ordering': ['-last_extended_at', '-posted_at'], 'verbose_name': 'ვაკანსია', 'verbose_name_plural': 'ვაკანსიები'},
        ),
        migrations.AddField(
            model_name='joblisting',
            name='last_extended_at',
            field=models.DateTimeField(blank=True, db_index=True, null=True, verbose_name='ბოლოს გაგრძელების თარიღი'),
        ),
        migrations.AddIndex(
            model_name='joblisting',
            index=models.Index(fields=['last_extended_at'], name='core_joblis_last_ex_86af33_idx'),
        ),
    ]
