# Generated by Django 5.1.7 on 2025-06-30 17:34

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0065_alter_joblisting_options_joblisting_last_extended_at_and_more'),
    ]

    operations = [
    ]
