# Generated by Django 5.1.7 on 2025-06-30 17:45

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0066_auto_20250630_2134'),
    ]

    operations = [
        migrations.AlterField(
            model_name='joblisting',
            name='last_extended_at',
            field=models.DateTimeField(blank=True, null=True, verbose_name='ბოლო გაგრძელების თარიღი'),
        ),
    ]
