# Generated by Django 5.1.7 on 2025-07-01 20:00

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0068_make_fields_nullable'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='joblisting',
            name='fields',
        ),
        migrations.RemoveField(
            model_name='joblisting',
            name='interests',
        ),
        migrations.CreateModel(
            name='EmployerNotification',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('job_title', models.CharField(blank=True, max_length=255, null=True, verbose_name='ვაკანსიის სათაური')),
                ('notification_type', models.CharField(choices=[('job_status_update', 'Job Status Update'), ('new_application', 'New Application')], max_length=50, verbose_name='შეტყობინების ტიპი')),
                ('message', models.TextField(verbose_name='შეტყობინება')),
                ('is_read', models.BooleanField(db_index=True, default=False, verbose_name='წაკითხულია')),
                ('created_at', models.DateTimeField(auto_now_add=True, db_index=True, verbose_name='შექმნის თარიღი')),
                ('employer_profile', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='notifications', to='core.employerprofile', verbose_name='დამსაქმებელი')),
                ('job', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='notifications', to='core.joblisting', verbose_name='ვაკანსია')),
            ],
            options={
                'verbose_name': 'დამსაქმებლის შეტყობინება',
                'verbose_name_plural': 'დამსაქმებლის შეტყობინებები',
                'ordering': ['-created_at'],
                'indexes': [models.Index(fields=['employer_profile', 'is_read'], name='core_employ_employe_475455_idx'), models.Index(fields=['job', 'notification_type'], name='core_employ_job_id_9f6a9c_idx')],
            },
        ),
    ]
