# Generated by Django 5.1.7 on 2025-07-01 20:50

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0069_remove_joblisting_fields_remove_joblisting_interests_and_more'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='CandidateNotification',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('job_title', models.CharField(blank=True, max_length=255, null=True, verbose_name='ვაკანსიის სათაური')),
                ('company_name', models.CharField(blank=True, max_length=255, null=True, verbose_name='კომპანია')),
                ('notification_type', models.CharField(choices=[('application_status_update', 'Application Status Update'), ('interview_invitation', 'Interview Invitation')], max_length=50, verbose_name='შეტყობინების ტიპი')),
                ('message', models.TextField(verbose_name='შეტყობინება')),
                ('is_read', models.BooleanField(db_index=True, default=False, verbose_name='წაკითხულია')),
                ('created_at', models.DateTimeField(auto_now_add=True, db_index=True, verbose_name='შექმნის თარიღი')),
                ('application', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='candidate_notifications', to='core.jobapplication', verbose_name='აპლიკაცია')),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='notifications', to=settings.AUTH_USER_MODEL, verbose_name='მომხმარებელი')),
            ],
            options={
                'verbose_name': 'კანდიდატის შეტყობინება',
                'verbose_name_plural': 'კანდიდატის შეტყობინებები',
                'ordering': ['-created_at'],
                'indexes': [models.Index(fields=['user', 'is_read'], name='core_candid_user_id_c85023_idx'), models.Index(fields=['application', 'notification_type'], name='core_candid_applica_e05f50_idx')],
            },
        ),
    ]
