# Generated by Django 5.1.7 on 2025-07-04 22:50

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0071_fix_rejection_reasons'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='rejectionreason',
            name='code',
        ),
        migrations.AlterField(
            model_name='rejectionreason',
            name='name',
            field=models.CharField(max_length=255, unique=True, verbose_name='მიზეზი'),
        ),
    ]
