# Generated by Django 5.1.7 on 2025-07-12 22:19

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0072_remove_rejectionreason_code_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='userprofile',
            name='phone_number',
            field=models.CharField(blank=True, max_length=50, null=True, verbose_name='მობილურის ნომერი'),
        ),
    ]
