# Generated by Django 5.1.7 on 2025-08-27 16:53

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0073_userprofile_phone_number'),
    ]

    operations = [
        migrations.CreateModel(
            name='ComparisonRowTranslation',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('language_code', models.CharField(choices=[('ka', 'Georgian'), ('en', 'English'), ('ru', 'Russian')], max_length=2, verbose_name='Language')),
                ('feature_name', models.CharField(blank=True, max_length=255, verbose_name='Translated Feature Name')),
                ('standard_value', models.CharField(blank=True, max_length=255, verbose_name='Translated Standard Value')),
                ('premium_value', models.CharField(blank=True, max_length=255, verbose_name='Translated Premium Value')),
                ('premium_plus_value', models.CharField(blank=True, max_length=255, verbose_name='Translated Premium Plus Value')),
                ('row', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='translations', to='core.comparisonrow', verbose_name='Row')),
            ],
            options={
                'verbose_name': 'Comparison Row Translation',
                'verbose_name_plural': 'Comparison Row Translations',
                'ordering': ['row__display_order', 'language_code'],
                'unique_together': {('row', 'language_code')},
            },
        ),
        migrations.CreateModel(
            name='ComparisonTableTranslation',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('language_code', models.CharField(choices=[('ka', 'Georgian'), ('en', 'English'), ('ru', 'Russian')], max_length=2, verbose_name='Language')),
                ('title', models.CharField(blank=True, max_length=255, verbose_name='Translated Title')),
                ('subtitle', models.CharField(blank=True, max_length=255, verbose_name='Translated Subtitle')),
                ('table', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='translations', to='core.comparisontable', verbose_name='Table')),
            ],
            options={
                'verbose_name': 'Comparison Table Translation',
                'verbose_name_plural': 'Comparison Table Translations',
                'ordering': ['table__id', 'language_code'],
                'unique_together': {('table', 'language_code')},
            },
        ),
        migrations.CreateModel(
            name='PricingFeatureTranslation',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('language_code', models.CharField(choices=[('ka', 'Georgian'), ('en', 'English'), ('ru', 'Russian')], max_length=2, verbose_name='Language')),
                ('text', models.CharField(blank=True, max_length=255, verbose_name='Translated Text')),
                ('feature', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='translations', to='core.pricingfeature', verbose_name='Feature')),
            ],
            options={
                'verbose_name': 'Pricing Feature Translation',
                'verbose_name_plural': 'Pricing Feature Translations',
                'ordering': ['feature__display_order', 'language_code'],
                'unique_together': {('feature', 'language_code')},
            },
        ),
        migrations.CreateModel(
            name='PricingPackageTranslation',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('language_code', models.CharField(choices=[('ka', 'Georgian'), ('en', 'English'), ('ru', 'Russian')], max_length=2, verbose_name='Language')),
                ('name', models.CharField(blank=True, max_length=100, verbose_name='Translated Name')),
                ('description', models.CharField(blank=True, max_length=255, verbose_name='Translated Description')),
                ('package', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='translations', to='core.pricingpackage', verbose_name='Package')),
            ],
            options={
                'verbose_name': 'Pricing Package Translation',
                'verbose_name_plural': 'Pricing Package Translations',
                'ordering': ['package__display_order', 'language_code'],
                'unique_together': {('package', 'language_code')},
            },
        ),
    ]
