# Generated by Django 5.1.7 on 2025-08-27 17:02

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0074_comparisonrowtranslation_comparisontabletranslation_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='comparisonrowtranslation',
            name='language_code',
            field=models.CharField(choices=[('ka', 'Georgian'), ('en', 'English')], max_length=2, verbose_name='Language'),
        ),
        migrations.AlterField(
            model_name='comparisontabletranslation',
            name='language_code',
            field=models.CharField(choices=[('ka', 'Georgian'), ('en', 'English')], max_length=2, verbose_name='Language'),
        ),
        migrations.AlterField(
            model_name='pricingfeaturetranslation',
            name='language_code',
            field=models.CharField(choices=[('ka', 'Georgian'), ('en', 'English')], max_length=2, verbose_name='Language'),
        ),
        migrations.AlterField(
            model_name='pricingpackagetranslation',
            name='language_code',
            field=models.CharField(choices=[('ka', 'Georgian'), ('en', 'English')], max_length=2, verbose_name='Language'),
        ),
    ]
